Get rid of duplicated 'Build failed due to failed dependency' error messages
This was spamming a gazillion duplicated error messages to stderr:

error: Build failed due to failed dependency
error: Build failed due to failed dependency
error: Build failed due to failed dependency
error: Build failed due to failed dependency
error: Build failed due to failed dependency
error: Build failed due to failed dependency

Notably, it was just duplicating the more detailed errors above.