libstore: Fix LocalStore::openGCLock error check
Ran into a bug with an unhelpful error message:

error: acquiring/releasing lock: Bad file descriptor

The error conditions was inverted, since fdGCLock was the file descriptor
and not an AutoCloseFD.